### ISSUE TITLE
Create `v1.3.0` tag

### ISSUE THREAD

**Issue by jpmcb** [spf13/cobra-cli#7]
In support of https://github.com/spf13/cobra/issues/1597, we want to tag this repository with the same "version" that was used before we migrated the code here. This still communicates the version of the cobra CLI but also represents the final tag that the two will correlate.

In otherwords, this tag is the split in the road that will enable use to seperate `cobra` from `cobra-cli`

The release note for `v1.3.0` of this repo will note that all previous history and release markers can be tracked in the `spf13/cobra` repo.

If there are no objections, I will do this within the week 👀

**Comment by marckhouzam** [comment]
As mentioned, it makes sense to me that `cobra-cli` 1.3 should be "exactly" the same as the `cobra` generator 1.3 except for the renaming.

That being said I'm not sure what's best about supporting the `.cobra-cli.yaml` configuration file of #6.  Should it be in 1.3 or not?

**Comment by johnSchnake** [comment]
Why not start with a 1.3.1 with the minor changes from the move? There isn't any particular reason why we need the 1.3 to live in both places and in the worst case it would make for some frustrations if they differed slightly between the repos.

**Comment by jpmcb** [comment]
What if we cut `v1.3.0` which is _exactly_ what was in `spf13/cobra` 

and then cut a quick followup of `v1.3.1` with any _"fixes"_ that make sense for this repo?

**Comment by johnSchnake** [comment]
But what is the point of the v1.3.0? If its exact (same sha for the build) then no user could possibly need it. If its not the same then it should be v1.3.1, right?

**Comment by jpmcb** [comment]
I guess I'm not sure the benefit either; just thought it'd click nicely with where `spf13/cobra` is at right now

@johnSchnake @marckhouzam - we good to cut a `v1.3.0` tag today?

**Comment by marckhouzam** [comment]
I do like that we have a tag that corresponds to the 1.3.0 release of the spf13/cobra repo (although the code is slightly different because of the renaming).  We can do 1.3.1 release quickly after to deal with the renaming of the configuration file and possibly some other small improvements.

So it's 👍 for me @jpmcb

**Comment by liggitt** [comment]
👍  from me as well to have a 1.3.0 that is the ~same as cobra 1.3.0 modulo rename

**Comment by jpmcb** [comment]
Sounds good to me - `v1.3.0` incoming today! 👀

**Comment by jpmcb** [comment]
Tagged and released! https://github.com/spf13/cobra-cli/releases/tag/v1.3.0
