### ISSUE TITLE
latest version cobra-cli:  command not found 

### ISSUE THREAD

**Issue by zhongsdjn** [spf13/cobra-cli#70]
```
mkdir myapp
cd myapp
go mod init github.com/spf13/myapp

go get -u github.com/spf13/cobra@latest
go install github.com/spf13/cobra-cli@latest
```

When I excute `cobra-cli init `, -bash: cobra-cli: command not found
windows system:   'cobra-cli' is not recognized as an internal or external command,
operable program or batch file.
why？  A month ago is normal!

**Comment by marckhouzam** [comment]
Normally `go install` will put the binary under `$GOPATH/bin`.

You have to make sure `$GOPATH/bin` is found on your PATH variable.

**Comment by zhongsdjn** [comment]
> Normally `go install` will put the binary under `$GOPATH/bin`.
> 
> You have to make sure `$GOPATH/bin` is found on your PATH variable.

ok! I see!
